apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: project-airgap-files
spec:
  files:
    - path: https://raw.githubusercontent.com/zackbradys/project-airgap/main/files/rancher-cluster-templates-aws.md
      name: rancher-cluster-templates-aws.md
    - path: https://raw.githubusercontent.com/zackbradys/project-airgap/main/files/rancher-cluster-templates-values.yaml
      name: rancher-cluster-templates-values.yaml
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: project-airgap-charts
spec:
  charts:
    - name: rancher-cluster-templates
      repoURL: https://rancherfederal.github.io/rancher-cluster-templates
      version: 0.4.3
---
# apiVersion: content.hauler.cattle.io/v1alpha1
# kind: Images
# metadata:
#   name: project-airgap-images
# spec:
#   images:
#     - name: test
